// frontend/src/components/Navbar.jsx
import * as React from 'react';
import AppBar from '@mui/material/AppBar';
import Button from '@mui/material/Button';
import Toolbar from '@mui/material/Toolbar';
import Menu from '@mui/material/Menu';
import MenuItem from '@mui/material/MenuItem';
import Tabs from '@mui/material/Tabs';
import Tab from '@mui/material/Tab';
import AccountCircleIcon from '@mui/icons-material/AccountCircle';
import Link from "@mui/material/Link";
import {
  Link as RouterLink,
  useLocation,
} from 'react-router-dom';

export default function Navbar({user}) {
  const [anchorEl, setAnchorEl] = React.useState(null);
  const { pathname } = useLocation();
  const open = Boolean(anchorEl);
  const handleClick = (event) => {
    setAnchorEl(event.currentTarget);
  };
  const handleClose = () => {
    setAnchorEl(null);
  };
  return (
    <AppBar position="sticky">
      <Toolbar variant="dense" disableGutters>
        <Tabs value={pathname} sx={{flexGrow: 1}} textColor="inherit" TabIndicatorProps={{style: {backgroundColor: 'black'}}}>
          <Tab label="Avaleht" value="/" to="/" component={RouterLink}/>
          <Tab label="Lisa retsept" value="/add-recipe" to="/add-recipe" component={RouterLink}/>
          <Tab label="Otsing" href="/index-vue.html#/search"/>
          <Tab label="Nädalaplaan" value="/weekplan" to="/weekplan" component={RouterLink}/>
        </Tabs>
        <Button startIcon={<AccountCircleIcon />} color="inherit" onClick={handleClick}>
          {user.username}
        </Button>
        <Menu
          id="basic-menu"
          anchorEl={anchorEl}
          open={open}
          onClose={handleClose}
        >
          <MenuItem component={Link} href="/index-vue.html#/user" onClick={handleClose}>Muuda parooli</MenuItem>
          {user.isAdmin && <MenuItem component={Link} href="/index-vue.html#/admin" onClick={handleClose}>Halda kasutajaid</MenuItem>}
          <MenuItem component={Link} href="/logout" onClick={handleClose}>Logi välja</MenuItem>
        </Menu>

      </Toolbar>
    </AppBar>
  );
}

// frontend-vue/src/components/Navbar.vue
<template>
  <!--<div id="navbar">-->
  <md-app-toolbar class="md-primary md-dense">
    <div class="md-toolbar-section-start">
      <md-tabs md-sync-route class="md-primary">
        <md-tab md-label="Avaleht" href="/"></md-tab>
        <md-tab md-label="Lisa retsept" to="/addrecipe"></md-tab>
        <md-tab md-label="Otsing" to="/search"></md-tab>
      </md-tabs>
    </div>
    <div class="md-toolbar-section-end">
      <md-menu md-direction="bottom-start">
        <md-button md-menu-trigger><md-icon md-src="/static/icons/baseline-account_circle-24px.svg"/>{{ user.username }}</md-button>
        <md-menu-content>
          <md-menu-item to="/user">Muuda parooli</md-menu-item>
          <md-menu-item v-if="user && user.isAdmin" to="/admin">Halda kasutajaid</md-menu-item>
          <md-menu-item href="/logout">Logi välja</md-menu-item>
        </md-menu-content>
      </md-menu>
    </div>

  </md-app-toolbar>
  <!--</div>-->
</template>
<style scoped lang="scss">
  /*.md-toolbar {*/
    /*position: fixed;*/
  /*}*/
  /*#navbar{*/
    /*background-color:#009900;*/
    /*text-align: left;*/
    /*width: 100%;*/
    /*font-size: 0;*/
  /*}*/

  /*span {*/
    /*text-align: right;*/
    /*font-family: Verdana,Geneva,sans-serif;*/
    /*color: #ffffff;*/
    /*font-size: 20px;*/
    /*padding: 15px;*/
    /*position: absolute;*/
    /*right: 15px;*/
  /*}*/
  /*.logout {*/
    /*font-size:20px;*/
    /*padding: 0px;*/
  /*}*/

  /*.logout:hover {*/
    /*text-decoration: underline;*/
    /*background-color: inherit;*/
  /*}*/
  /*a {*/
    /*text-decoration: none;*/
    /*font-family: Verdana,Geneva,sans-serif;*/
    /*color: #ffffff;*/
    /*font-size: 30px;*/
    /*padding: 10px;*/
    /*display: inline-block;*/
  /*}*/

  /*a:hover {*/
    /*background-color:#005500;*/
  /*}*/

  /*.router-link-active {*/
    /*background-color:#007700;*/
  /*}*/
</style>
<script>
  import { store } from "../datastore.js";
  export default{
    name: "navbar",
    data: function () {
      console.log(store);
      return store;
    }
  };
</script>
